# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT
fabric_version=0.152.2+26.2
# Mod Properties
mod_version=5.1
maven_group=com.farsight
archives_base_name=farsight